from __future__ import annotations

from datetime import date, timedelta

from src.models import (
    ClaimMode,
    ClaimRecord,
    DailyMetric,
    Decision,
    DocumentArtifact,
    Evidence,
    Financials,
    PatientInfo,
    ProviderInfo,
    RuleResult,
    TimelineEvent,
)


def build_mock_claims() -> list[ClaimRecord]:
    return [
        ClaimRecord(
            claim_id="CN001",
            mode=ClaimMode.MOCK,
            status=Decision.FAIL,
            confidence=0.89,
            complexity_score=81,
            patient=PatientInfo(
                patient_name="Anand Verma",
                patient_id="UHID-CN001",
                age=58,
                gender="Male",
            ),
            provider=ProviderInfo(
                hospital_name="Metro Cardiac Institute",
                treating_doctor="Dr. S. Iyer",
                state="Karnataka",
            ),
            payer="NHA",
            tpa="Ayushman Bharat",
            diagnosis="Coronary artery disease",
            procedures=["Angioplasty"],
            admission_date=date(2026, 2, 2),
            discharge_date=date(2026, 2, 6),
            length_of_stay_days=4,
            documents=[
                DocumentArtifact(
                    doc_id="D1",
                    file_name="D1.pdf",
                    page_number=1,
                    doc_type="Discharge summary",
                    language="English",
                    quality="High",
                    summary="Includes admission and discharge dates and the final diagnosis.",
                ),
                DocumentArtifact(
                    doc_id="D1",
                    file_name="D1.pdf",
                    page_number=2,
                    doc_type="Clinical note",
                    language="English",
                    quality="Medium",
                    summary="Post-procedure monitoring notes and nursing observations.",
                ),
                DocumentArtifact(
                    doc_id="D1",
                    file_name="D1.pdf",
                    page_number=3,
                    doc_type="Angioplasty report",
                    language="English",
                    quality="High",
                    summary="Procedure details and intervention timestamp.",
                ),
                DocumentArtifact(
                    doc_id="D2",
                    file_name="D2.pdf",
                    page_number=1,
                    doc_type="Xray",
                    language="English",
                    quality="Medium",
                    summary="Diagnostic imaging supporting pre-procedure workup.",
                ),
                DocumentArtifact(
                    doc_id="D3",
                    file_name="D3.pdf",
                    page_number=1,
                    doc_type="CT Scan",
                    language="English",
                    quality="Medium",
                    summary="Diagnostic investigation before intervention.",
                ),
                DocumentArtifact(
                    doc_id="D4",
                    file_name="d4.png",
                    page_number=1,
                    doc_type="Patient Photo",
                    language="N/A",
                    quality="Low",
                    summary="Patient identity image with no adjudication relevance.",
                    required=False,
                    extra_document=True,
                ),
                DocumentArtifact(
                    doc_id="D4",
                    file_name="d4.png",
                    page_number=1,
                    doc_type="Angioplasty",
                    language="N/A",
                    quality="Low",
                    summary="Non-required image variant not needed for clinical or claim validation.",
                    required=False,
                    extra_document=True,
                ),
            ],
            timeline=[
                TimelineEvent(
                    sequence=1,
                    label="Admission",
                    event_date="02-Feb-26",
                    source_doc_id="D1",
                    source_label="Discharge Summary",
                    temporal_validity="Valid",
                    confidence=0.96,
                ),
                TimelineEvent(
                    sequence=2,
                    label="Diagnostic Investigation",
                    event_date="02-Feb-26",
                    source_doc_id="D3/D2",
                    source_label="CT Scan / X-ray",
                    temporal_validity="Before procedure",
                    confidence=0.90,
                ),
                TimelineEvent(
                    sequence=3,
                    label="Procedure (Package)",
                    event_date="03-Feb-26",
                    source_doc_id="D1",
                    source_label="Angioplasty Report",
                    temporal_validity="Valid",
                    confidence=0.95,
                ),
                TimelineEvent(
                    sequence=4,
                    label="Post-Procedure Monitoring",
                    event_date="04-05-Feb-2026",
                    source_doc_id="D1",
                    source_label="Clinical Notes",
                    temporal_validity="Valid",
                    confidence=0.88,
                ),
                TimelineEvent(
                    sequence=5,
                    label="Discharge",
                    event_date="06-Feb-26",
                    source_doc_id="D1",
                    source_label="Discharge Summary",
                    temporal_validity="After treatment",
                    confidence=0.97,
                ),
            ],
            rules=[
                RuleResult(
                    rule_id="TEMP-001",
                    title="Admission date must not be after surgery date",
                    passed=False,
                    severity="High",
                    rationale="Documented chronology is inconsistent: one extracted surgery timestamp precedes admission.",
                    evidence=[
                        Evidence(
                            source_doc_id="D1",
                            page_number=1,
                            bounding_box="[0.13,0.25,0.49,0.44]",
                            snippet="Admission date extracted as 02-Feb-26; surgery timestamp variant indicates 01-Feb-26.",
                            confidence=0.86,
                        )
                    ],
                ),
                RuleResult(
                    rule_id="STG-ANGIO-004",
                    title="Clinical rules as per STG should match angioplasty package",
                    passed=False,
                    severity="High",
                    rationale="Submitted diagnostic and clinical indicators do not fully satisfy the expected STG pathway for the claimed package.",
                    evidence=[
                        Evidence(
                            source_doc_id="D3",
                            page_number=1,
                            bounding_box="[0.22,0.16,0.74,0.62]",
                            snippet="CT and X-ray support workup, but mandatory corroborating clinical detail is incomplete.",
                            confidence=0.83,
                        )
                    ],
                ),
                RuleResult(
                    rule_id="DOC-EXTRA-002",
                    title="Extra or non-required documents should be flagged",
                    passed=True,
                    severity="Medium",
                    rationale="Patient photo and duplicate angioplasty image were identified as non-required for claim validation.",
                    evidence=[
                        Evidence(
                            source_doc_id="D4",
                            page_number=1,
                            bounding_box="[0.08,0.12,0.82,0.90]",
                            snippet="Visual content classified as patient photo / non-essential supporting image.",
                            confidence=0.91,
                        )
                    ],
                ),
            ],
            financials=Financials(
                claimed_amount=125000,
                approved_amount=0,
                package_code="CARD-401",
                package_name="Angioplasty",
            ),
            extracted_fields={
                "patient_name": "Anand Verma",
                "diagnosis": "Coronary artery disease",
                "procedure": "Angioplasty",
                "hospital_stamp": "Detected",
                "doctor_signature": "Detected",
                "barcode": "Not found",
                "document_classification_f1_target": ">= 0.95",
                "rules_and_provenance_f1_target": ">= 0.96",
                "solution_design_f1_target": ">= 0.93",
            },
            notes=[
                "Two non-required supporting images were flagged automatically.",
                "Timeline assembled successfully, but chronology conflict remains a hard-stop rule failure.",
            ],
            recommended_action="Fail claim and request corrected chronology plus STG-aligned clinical evidence.",
            scoring_summary={
                "Document Classification": "Weight 40% | Rank 1 target F1 >= 0.95",
                "Rule Logic and Provenance": "Weight 40% | Rank 1 target F1 >= 0.96",
                "Solution Design": "Weight 20% | Rank 1 target F1 >= 0.93",
            },
            escalation_reason="Temporal inconsistency and STG mismatch.",
        ),
        ClaimRecord(
            claim_id="CLM-2026-0002",
            mode=ClaimMode.MOCK,
            status=Decision.CONDITIONAL,
            confidence=0.68,
            complexity_score=73,
            patient=PatientInfo(
                patient_name="S. Lakshmi",
                patient_id="UHID-11007",
                age=61,
                gender="Female",
            ),
            provider=ProviderInfo(
                hospital_name="Sunrise Ortho Centre",
                treating_doctor="Dr. Arvind Rao",
                state="Karnataka",
            ),
            payer="NHA",
            tpa="MediAssist",
            diagnosis="Intertrochanteric fracture femur",
            procedures=["Open reduction internal fixation"],
            admission_date=date(2026, 4, 1),
            discharge_date=date(2026, 4, 8),
            length_of_stay_days=7,
            documents=[
                DocumentArtifact(
                    doc_id="DOC-5",
                    file_name="implant_sticker_photo.jpg",
                    page_number=1,
                    doc_type="Implant Sticker",
                    language="English",
                    quality="High",
                    summary="Sticker partially visible; batch and lot number readable.",
                ),
                DocumentArtifact(
                    doc_id="DOC-6",
                    file_name="invoice_scan.pdf",
                    page_number=2,
                    doc_type="Invoice",
                    language="English",
                    quality="Low",
                    summary="Line items blurry with uncertain total and consumables split.",
                ),
            ],
            timeline=[
                TimelineEvent(
                    sequence=1,
                    label="Admission",
                    event_date="01-Apr-26",
                    source_doc_id="DOC-5",
                    source_label="Implant Case Sheet",
                    temporal_validity="Valid",
                    confidence=0.81,
                ),
                TimelineEvent(
                    sequence=2,
                    label="Procedure (Package)",
                    event_date="02-Apr-26",
                    source_doc_id="DOC-5",
                    source_label="Operative Note",
                    temporal_validity="Valid",
                    confidence=0.89,
                ),
                TimelineEvent(
                    sequence=3,
                    label="Discharge",
                    event_date="08-Apr-26",
                    source_doc_id="DOC-6",
                    source_label="Invoice",
                    temporal_validity="After treatment",
                    confidence=0.71,
                ),
            ],
            rules=[
                RuleResult(
                    rule_id="IMPL-004",
                    title="Implant evidence available",
                    passed=True,
                    severity="High",
                    rationale="Implant sticker detected, but one identifier field is partially occluded.",
                ),
                RuleResult(
                    rule_id="FIN-002",
                    title="Invoice amount consistent with package",
                    passed=False,
                    severity="High",
                    rationale="Invoice OCR confidence is low and line-item breakup cannot be reconciled to claimed amount.",
                ),
            ],
            financials=Financials(
                claimed_amount=128000,
                approved_amount=0,
                package_code="ORTHO-315",
                package_name="Femur Fracture Fixation",
            ),
            extracted_fields={
                "implant_sticker": "Detected with partial occlusion",
                "doctor_signature": "Detected",
                "barcode": "Detected",
            },
            notes=["Manual review required due to low-confidence financial extraction."],
            recommended_action="Send to manual review with invoice reconciliation priority.",
            escalation_reason="Low-confidence financial extraction and package reconciliation.",
        ),
        # PASS Claim - Orthopedic
        ClaimRecord(
            claim_id="CLM-2026-0003",
            mode=ClaimMode.MOCK,
            status=Decision.PASS,
            confidence=0.94,
            complexity_score=42,
            patient=PatientInfo(
                patient_name="Rajesh Kumar",
                patient_id="UHID-2024-0345",
                age=45,
                gender="Male",
            ),
            provider=ProviderInfo(
                hospital_name="Apollo Hospitals Chennai",
                treating_doctor="Dr. Suresh Menon",
                state="Tamil Nadu",
            ),
            payer="NHA",
            tpa="Bajaj Allianz",
            diagnosis="Meniscus tear",
            procedures=["Arthroscopic meniscectomy"],
            admission_date=date(2026, 3, 15),
            discharge_date=date(2026, 3, 19),
            length_of_stay_days=4,
            documents=[
                DocumentArtifact(
                    doc_id="DOC-10",
                    file_name="discharge_summary.pdf",
                    page_number=1,
                    doc_type="Discharge summary",
                    language="English",
                    quality="High",
                    summary="Clean discharge with all procedural details.",
                ),
                DocumentArtifact(
                    doc_id="DOC-11",
                    file_name="operative_report.pdf",
                    page_number=1,
                    doc_type="Operative Report",
                    language="English",
                    quality="High",
                    summary="Detailed operative notes with timestamps.",
                ),
            ],
            timeline=[
                TimelineEvent(
                    sequence=1,
                    label="Admission",
                    event_date="15-Mar-26",
                    source_doc_id="DOC-10",
                    source_label="Admission Sheet",
                    temporal_validity="Valid",
                    confidence=0.98,
                ),
                TimelineEvent(
                    sequence=2,
                    label="Procedure (Package)",
                    event_date="16-Mar-26",
                    source_doc_id="DOC-11",
                    source_label="Operative Report",
                    temporal_validity="Valid",
                    confidence=0.97,
                ),
                TimelineEvent(
                    sequence=3,
                    label="Discharge",
                    event_date="19-Mar-26",
                    source_doc_id="DOC-10",
                    source_label="Discharge Summary",
                    temporal_validity="After treatment",
                    confidence=0.99,
                ),
            ],
            rules=[
                RuleResult(
                    rule_id="CHRONO-001",
                    title="Chronology validation",
                    passed=True,
                    severity="High",
                    rationale="All dates are in proper chronological order.",
                ),
                RuleResult(
                    rule_id="LOS-CHECK-001",
                    title="Length of stay within limits",
                    passed=True,
                    severity="High",
                    rationale="4 days LoS is within standard limits for arthroscopic procedures.",
                ),
                RuleResult(
                    rule_id="FIN-001",
                    title="Claimed amount matches package",
                    passed=True,
                    severity="High",
                    rationale="INR 45,000 is within approved package limit for arthroscopy.",
                ),
            ],
            financials=Financials(
                claimed_amount=45000,
                approved_amount=45000,
                package_code="ORTHO-201",
                package_name="Arthroscopic Meniscectomy",
            ),
            extracted_fields={
                "hospital_stamp": "Detected",
                "doctor_signature": "Detected",
                "barcode": "Detected",
            },
            notes=[],
            recommended_action="Approve claim - all validations passed.",
            scoring_summary={
                "Documentation Quality": "Excellent - All required docs present",
                "Rule Compliance": "100% - All rules passed",
                "Financial Accuracy": "Verified - Within package limits",
            },
        ),
        # CONDITIONAL Claim - Cardiac
        ClaimRecord(
            claim_id="CLM-2026-0004",
            mode=ClaimMode.MOCK,
            status=Decision.CONDITIONAL,
            confidence=0.71,
            complexity_score=78,
            patient=PatientInfo(
                patient_name="Priya Sharma",
                patient_id="UHID-2024-0567",
                age=52,
                gender="Female",
            ),
            provider=ProviderInfo(
                hospital_name="Max Healthcare Mumbai",
                treating_doctor="Dr. Vikram Singh",
                state="Maharashtra",
            ),
            payer="NHA",
            tpa="ICICI Lombard",
            diagnosis="Atrial fibrillation",
            procedures=["Catheter ablation"],
            admission_date=date(2026, 3, 22),
            discharge_date=date(2026, 3, 25),
            length_of_stay_days=3,
            documents=[
                DocumentArtifact(
                    doc_id="DOC-15",
                    file_name="pre_procedure_echo.pdf",
                    page_number=1,
                    doc_type="Echocardiography",
                    language="English",
                    quality="Medium",
                    summary="Echo report with borderline findings.",
                ),
                DocumentArtifact(
                    doc_id="DOC-16",
                    file_name="procedure_note.pdf",
                    page_number=1,
                    doc_type="Procedure Note",
                    language="English",
                    quality="High",
                    summary="Ablation details documented.",
                ),
            ],
            timeline=[
                TimelineEvent(
                    sequence=1,
                    label="Admission",
                    event_date="22-Mar-26",
                    source_doc_id="DOC-15",
                    source_label="Admission Notes",
                    temporal_validity="Valid",
                    confidence=0.92,
                ),
                TimelineEvent(
                    sequence=2,
                    label="Pre-procedure Imaging",
                    event_date="22-Mar-26",
                    source_doc_id="DOC-15",
                    source_label="Echocardiography",
                    temporal_validity="Valid",
                    confidence=0.88,
                ),
                TimelineEvent(
                    sequence=3,
                    label="Procedure (Package)",
                    event_date="23-Mar-26",
                    source_doc_id="DOC-16",
                    source_label="Procedure Note",
                    temporal_validity="Valid",
                    confidence=0.95,
                ),
                TimelineEvent(
                    sequence=4,
                    label="Discharge",
                    event_date="25-Mar-26",
                    source_doc_id="DOC-16",
                    source_label="Discharge Summary",
                    temporal_validity="After treatment",
                    confidence=0.91,
                ),
            ],
            rules=[
                RuleResult(
                    rule_id="ECHO-002",
                    title="Pre-procedure echo findings document AFib",
                    passed=True,
                    severity="High",
                    rationale="Echo confirms atrial fibrillation diagnosis.",
                ),
                RuleResult(
                    rule_id="FIN-AFB-001",
                    title="Financial amount needs verification",
                    passed=False,
                    severity="Medium",
                    rationale="Claimed INR 180,000 is at upper limit; needs cardiology team review.",
                ),
            ],
            financials=Financials(
                claimed_amount=180000,
                approved_amount=0,
                package_code="CARD-501",
                package_name="Catheter Ablation AF",
            ),
            extracted_fields={
                "hospital_stamp": "Detected",
                "doctor_signature": "Detected",
                "procedure_code": "Verified",
            },
            notes=["Requires specialist cardiology review due to high claimed amount."],
            recommended_action="Route to specialist for amount verification and approval.",
            escalation_reason="Financial limit verification needed.",
        ),
        # FAIL Claim - Trauma
        ClaimRecord(
            claim_id="CLM-2026-0005",
            mode=ClaimMode.MOCK,
            status=Decision.FAIL,
            confidence=0.82,
            complexity_score=88,
            patient=PatientInfo(
                patient_name="Ahmed Hassan",
                patient_id="UHID-2024-0789",
                age=35,
                gender="Male",
            ),
            provider=ProviderInfo(
                hospital_name="Fortis Hospital Bangalore",
                treating_doctor="Dr. Ramesh Reddy",
                state="Karnataka",
            ),
            payer="NHA",
            tpa="United India",
            diagnosis="Polytrauma with multiple fractures",
            procedures=["Open reduction fixation - multiple sites"],
            admission_date=date(2026, 2, 10),
            discharge_date=date(2026, 2, 25),
            length_of_stay_days=15,
            documents=[
                DocumentArtifact(
                    doc_id="DOC-20",
                    file_name="trauma_report.pdf",
                    page_number=1,
                    doc_type="Trauma Assessment",
                    language="English",
                    quality="Medium",
                    summary="Initial assessment of multiple injuries.",
                ),
                DocumentArtifact(
                    doc_id="DOC-21",
                    file_name="invoice_detailed.pdf",
                    page_number=1,
                    doc_type="Invoice",
                    language="English",
                    quality="Low",
                    summary="Unclear breakdown; implants cost not itemized.",
                ),
            ],
            timeline=[
                TimelineEvent(
                    sequence=1,
                    label="Admission",
                    event_date="10-Feb-26",
                    source_doc_id="DOC-20",
                    source_label="Emergency Report",
                    temporal_validity="Valid",
                    confidence=0.99,
                ),
                TimelineEvent(
                    sequence=2,
                    label="Emergency Procedure",
                    event_date="10-Feb-26",
                    source_doc_id="DOC-20",
                    source_label="OR Log",
                    temporal_validity="Valid",
                    confidence=0.94,
                ),
                TimelineEvent(
                    sequence=3,
                    label="Discharge",
                    event_date="25-Feb-26",
                    source_doc_id="DOC-20",
                    source_label="Discharge Summary",
                    temporal_validity="After treatment",
                    confidence=0.88,
                ),
            ],
            rules=[
                RuleResult(
                    rule_id="COVERAGE-POLY-001",
                    title="Polytrauma coverage exclusion check",
                    passed=False,
                    severity="High",
                    rationale="Polytrauma with 15-day LoS may exceed NHA coverage limits for this package.",
                ),
                RuleResult(
                    rule_id="FIN-IMPLANT-001",
                    title="Implant costs itemization",
                    passed=False,
                    severity="High",
                    rationale="Invoice does not itemize implant costs separately; cannot verify against approved list.",
                ),
            ],
            financials=Financials(
                claimed_amount=520000,
                approved_amount=0,
                package_code="TRAUMA-901",
                package_name="Polytrauma Management",
            ),
            extracted_fields={
                "hospital_stamp": "Detected",
                "doctor_signature": "Detected",
                "implant_sticker": "Not found in submitted docs",
            },
            notes=["Coverage limits exceeded.", "Implant verification missing."],
            recommended_action="Reject claim - coverage policy exclusion and missing implant verification.",
            escalation_reason="Policy coverage exclusion and incomplete financial documentation.",
        ),
        # PASS Claim - General Surgery
        ClaimRecord(
            claim_id="CLM-2026-0006",
            mode=ClaimMode.MOCK,
            status=Decision.PASS,
            confidence=0.91,
            complexity_score=38,
            patient=PatientInfo(
                patient_name="Sanjay Patel",
                patient_id="UHID-2024-0912",
                age=58,
                gender="Male",
            ),
            provider=ProviderInfo(
                hospital_name="Lilavati Hospital Mumbai",
                treating_doctor="Dr. Asha Kapoor",
                state="Maharashtra",
            ),
            payer="NHA",
            tpa="AIG",
            diagnosis="Cholelithiasis",
            procedures=["Laparoscopic cholecystectomy"],
            admission_date=date(2026, 3, 10),
            discharge_date=date(2026, 3, 12),
            length_of_stay_days=2,
            documents=[
                DocumentArtifact(
                    doc_id="DOC-25",
                    file_name="discharge.pdf",
                    page_number=1,
                    doc_type="Discharge summary",
                    language="English",
                    quality="High",
                    summary="Clear discharge with all documents attached.",
                ),
            ],
            timeline=[
                TimelineEvent(
                    sequence=1,
                    label="Admission",
                    event_date="10-Mar-26",
                    source_doc_id="DOC-25",
                    source_label="Admission",
                    temporal_validity="Valid",
                    confidence=0.99,
                ),
                TimelineEvent(
                    sequence=2,
                    label="Procedure (Package)",
                    event_date="11-Mar-26",
                    source_doc_id="DOC-25",
                    source_label="Operative Note",
                    temporal_validity="Valid",
                    confidence=0.98,
                ),
                TimelineEvent(
                    sequence=3,
                    label="Discharge",
                    event_date="12-Mar-26",
                    source_doc_id="DOC-25",
                    source_label="Discharge",
                    temporal_validity="After treatment",
                    confidence=0.99,
                ),
            ],
            rules=[
                RuleResult(
                    rule_id="CHRONO-GEN-001",
                    title="Chronology validation",
                    passed=True,
                    severity="High",
                    rationale="All dates aligned.",
                ),
                RuleResult(
                    rule_id="PROC-GEN-001",
                    title="Procedure matches diagnosis",
                    passed=True,
                    severity="High",
                    rationale="Cholecystectomy is appropriate for cholelithiasis.",
                ),
            ],
            financials=Financials(
                claimed_amount=32000,
                approved_amount=32000,
                package_code="GEN-101",
                package_name="Laparoscopic Cholecystectomy",
            ),
            extracted_fields={"hospital_stamp": "Detected"},
            notes=[],
            recommended_action="Approve - all criteria met.",
        ),
    ]


def build_daily_metrics() -> list[DailyMetric]:
    base = date(2026, 4, 6)
    rows = [
        (81, 49, 32, 37, 21, 23),
        (93, 57, 36, 42, 25, 26),
        (76, 43, 33, 34, 17, 25),
        (102, 65, 37, 50, 24, 28),
        (89, 58, 31, 44, 20, 25),
        (97, 61, 36, 48, 23, 26),
        (104, 69, 35, 55, 19, 30),
    ]
    metrics: list[DailyMetric] = []
    for index, row in enumerate(rows):
        total, auto, manual, passed, conditional, failed = row
        metrics.append(
            DailyMetric(
                metric_date=base + timedelta(days=index),
                total_claims=total,
                auto_adjudicated=auto,
                manual_review=manual,
                pass_count=passed,
                conditional_count=conditional,
                fail_count=failed,
            )
        )
    return metrics
